### ISSUE TITLE
Rename all variables to use "_" (underscore) instead of "-" (hyphen/dash) 

### ISSUE THREAD

**Issue by leodotcloud** [rancher/tf-rancher-up#104]
It's possible to pass the values to the variables using environment variables (Ex: export TF_VAR_secret_key="fillme"). But, we can't export a variable with hyphen/dash.

As a coding best practice, we should avoid using hyphen/dash in variable names. Not sure if there is a way to detect this using some tool and check it when a PR is created.

**Comment by dkeightley** [comment]
@BreakingPitt please feel free to create a PR to rename it wherever it shows up 👍

**Comment by leodotcloud** [comment]
Agree with @dkeightley, please feel free to create a PR @BreakingPitt.

**Comment by BreakingPitt** [comment]
@leodotcloud  @dkeightley I've opened a pull request #132 that addresses this issue.

**Comment by glovecchi0** [comment]
Problem solved with pr #132
