### ISSUE TITLE
Add descriptions to variables in variables.tf files 

### ISSUE THREAD

**Issue by sandipnikale** [rancher/tf-rancher-up#8]

**Comment by BreakingPitt** [comment]
@sandipnikale

I recently ran the following command  `grep -rnH --include="variables.tf" -A 2 "variable" .` to search for variable declarations in the existing `variables.tf` files within a fork of this repository and it seems that all the declared variables in `variables.tf` files have the description field filled.

To proceed further with the work, additional information is needed about where specifically a contributor should look for the description fields in the `variables.tf` files. 

Could you please provide more details? Maybe if the issue has been done before in previous commits, this issue can be closed.

Any guidance or additional context you can provide will be greatly appreciated.

Best regards

**Comment by sandipnikale** [comment]
Hi @BreakingPitt 
Yes, the descriptions were added as part of previous commits, i'll go ahead and close this, thanks
